project_id = "kufuqtpqiaupaxchdnsy"

[functions.process-qr-scan]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.monitor-event-activity]
verify_jwt = true

[functions.scan-cedula-ai]
verify_jwt = true